spring:
  application:
    name: bff-bob-a-thon
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Sao_Paulo

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

logging:
  level:
    root: INFO
    com.hackathon.bffbobathon: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Made with Bob
